version: '3.8'
services:
  app:
    image: java-benchmark:latest
    container_name: java-benchmark
    ports:
      - "8080:8080"
#    environment:
#      - JAVA_OPTS=-Xms512m -Xmx1024m
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "2GB"
        reservations:
          cpus: "1"
          memory: "1GB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "9999:9999"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'
networks:
  default:
    driver: bridge
    name: java_benchmark