version: '3.8'
services:
  app:
    image: java-benchmark-platform:latest
    container_name: java-benchmark-platform
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "2GB"
        reservations:
          cpus: "1"
          memory: "1GB"
